code: 0
swordName: Sword of Life
swordSpecialSword: 1
swordSpecialPower: 4
candiesNbrOwned: 27122
candiesNbrThrown: 1990
candiesNbrEaten: 745
candiesNbrTotal: 40449
candiesCandiesPerSecond: 5
candiesConverterActivated: 0
cauldronBookPage: 0
cauldronCandies: 0
cauldronLollipops: 0
chocolateBarsNbrOwned: 0
farmLollipopsPlanted: 203651
farmCurrentFlagIndex: 0
farmPlantingButtonsStep: 4
forgeStep: 2
shopLollipopsButtonsShown: 1
shopShown: 1
shopTicklingStep: 0
shopClickingOnLollipopStep: 0
hutStep: 2
hutSpeech: Here's 1139 candies for you !
inventoryMagicianHatLetter:      b
lollipopsNbrOwned: 361792
lollipopsNbrInStock: 140
lollipopsNbrBought: 29
mainNbrOfSecondsSinceLastMinInterval: 51
mainNbrOfSecondsSinceLastHourInterval: 3291
mainNbrOfSecondsSinceLastDayInterval: 17691
mountGoblinBasicChestProbability: 100
peacefulForestBasicChestProbability: 150
peacefulForestPoniesEncountered: 0
objectsHaveObjectKey: 1
objectsHaveObjectHutMap: 1
objectsHaveObjectWellMap: 1
objectsHaveObjectSwampMap: 1
objectsHaveObjectBoots: 1
objectsHaveObjectMagicianHat: 1
objectsHaveObjectPinkRing: 1
objectsHaveObjectForgeMap: 1
objectsHaveObjectCandiesConverter: 0
objectsHaveObjectPlateArmour: 0
objectsHaveObjectCauldron: 0
objectsHaveObjectMagicalHorn: 0
objectsHaveObjectHornOfPlenty: 0
objectsHaveObjectOldAmulet: 0
potionsShownHealth: 1
potionsShownEscape: 1
potionsShownBerserk: 1
potionsShownFireScroll: 0
potionsShownAcidRainScroll: 0
potionsShownTeleportScroll: 1
potionsShownEarthquakeScroll: 0
potionsShownImpInvocationScroll: 0
potionsShownMajorHealth: 0
potionsShownInvulnerability: 0
potionsShownTurtle: 0
potionsShownJelly: 0
potionsShownSeed: 0
potionsShownCloning: 0
potionsShownSuperman: 0
potionsShownGmooh: 0
potionsNbrOwnedHealth: 3
potionsNbrOwnedEscape: 2
potionsNbrOwnedBerserk: 5
potionsNbrOwnedFireScroll: 0
potionsNbrOwnedAcidRainScroll: 0
potionsNbrOwnedTeleportScroll: 1
potionsNbrOwnedEarthquakeScroll: 0
potionsNbrOwnedImpInvocationScroll: 0
potionsNbrOwnedMajorHealth: 0
potionsNbrOwnedInvulnerability: 0
potionsNbrOwnedTurtle: 0
potionsNbrOwnedJelly: 0
potionsNbrOwnedSeed: 0
potionsNbrOwnedCloning: 0
potionsNbrOwnedSuperman: 0
potionsNbrOwnedGmooh: 0
questMaxLandOrder: 3
questTiredTime: 0
spellsFasterCandiesFibo1: 5
spellsFasterCandiesFibo2: 8
swampStep: 17
tabsAnimation: slide
wishingWellSpeech: Multiplicatus, multiplicata, multiplicatum ! Your lollipops are now multiplied !
wishingWellStep: 2
yourselfCanSurpass: 0
developperComputerWon: 0